name: Stack

on:
  push:
  pull_request:

jobs:
  build:
    name: Stack CI - Linux - ${{ matrix.resolver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - resolver: lts-12
          - resolver: lts-14
          - resolver: lts-16
          - resolver: lts-17

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Install C dependencies
        run: |
          set -ex
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev \
            #

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and test
        run: |
          set -ex
          stack test \
            --fast --no-terminal \
            --resolver=${{ matrix.resolver }}
