name: Stack

on:
  push:
  pull_request:

jobs:
  build:
    name: Stack CI - Linux - ${{ matrix.resolver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - resolver: lts-12
            ghc: 8.4.4
          - resolver: lts-14
            ghc: 8.6.5
          - resolver: lts-16
            ghc: 8.8.4
          - resolver: lts-17
            ghc: 8.10.4

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Install C dependencies
        run: |
          set -ex
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev \
            #

      - name: Install GHC
        # use system ghc in stack, don't waste GH Actions cache space
        run: |
          set -ex
          sudo apt install -y ghc-${{ matrix.ghc }}
          echo /opt/ghc/${{ matrix.ghc }}/bin >> $GITHUB_PATH

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-${{ hashFiles('stack.yaml') }}-
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and test
        run: |
          set -ex
          stack test \
            --fast --no-terminal \
            --resolver=${{ matrix.resolver }} --system-ghc
